---
- name: Установка и настройка Zabbix Agent 2
  hosts: zabbix_agents
  become: yes
  vars:
    zabbix_version: "7.4"
    zabbix_server_ip: "10.0.0.10"
    zabbix_debian_url: "https://repo.zabbix.com/zabbix/7.4/release/debian/pool/main/z/zabbix-release/zabbix-release_latest_7.4+debian11_all.deb"
    zabbix_ubuntu_url: "https://repo.zabbix.com/zabbix/7.4/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest_7.4+ubuntu24.04_all.deb"
    zabbix_redos_package: "zabbix7-lts-agent"

  tasks:

    - name: Сбор сведения об ОС
      set_fact:
        is_debian: "{{ ansible_facts['distribution'] == 'Debian' }}"
        is_ubuntu: "{{ ansible_facts['distribution'] == 'Ubuntu' }}"
        is_redos: "{{ ansible_facts['distribution'] is search('RedOS') }}"

    - name: Устанавливаем lsb-release (для получения codename; заплатка)
      apt:
        name: lsb-release
        state: present
      when: is_debian or is_ubuntu

    - name: Debian/Ubuntu | Скачиваем zabbix-release.deb
      get_url:
        url: "{{ zabbix_debian_url if is_debian else zabbix_ubuntu_url }}"
        dest: /tmp/zabbix-release.deb
        mode: '0644'
      when: is_debian or is_ubuntu

    - name: Debian/Ubuntu | Устанавливаем zabbix-release.deb
      apt:
        deb: /tmp/zabbix-release.deb
      when: is_debian or is_ubuntu

    - name: Debian/Ubuntu | update
      apt:
        update_cache: yes
      when: is_debian or is_ubuntu

    - name: Debian/Ubuntu | Устанавливаем zabbix-agent2
      apt:
        name: zabbix-agent2
        state: presentсгук
      when: is_debian or is_ubuntu

    - name: RedOS | Устанавливаем Zabbix Agent
      dnf:
        name: "{{ zabbix_redos_package }}"
        state: present
      when: is_redos

    - name: Конф агента zabbix_agent*.conf
      copy:
        dest: >-
          {{ '/etc/zabbix/zabbix_agent2.conf' if is_debian or is_ubuntu else '/etc/zabbix/zabbix_agentd.conf' }}
        content: |
          Server={{ zabbix_server_ip }}
          ServerActive={{ zabbix_server_ip }}
          Hostname={{ inventory_hostname }}
          Include=/etc/zabbix/zabbix_agent2.d/*.conf
        mode: '0644'
      notify: Перезапустить Zabbix Agent
      when: is_debian or is_ubuntu or is_redos

    - name: Запускаем и включаем службу Zabbix Agent
      systemd:
        name: >-
          {{ 'zabbix-agent2' if is_debian or is_ubuntu else 'zabbix-agent' }}
        state: started
        enabled: yes
      when: is_debian or is_ubuntu or is_redos

  handlers:
    - name: Перезапустить Zabbix Agent
      systemd:
        name: >-
          {{ 'zabbix-agent2' if is_debian or is_ubuntu else 'zabbix-agent' }}
        state: restarted