---
- name: Установка Zabbix Agent 2 на CentOS 8
  hosts: centos8
  become: true
  vars:
    zabbix_major_version: "7.4"
    zabbix_server_ip: "10.0.0.10"

  tasks:
    - name: Добавляем репозиторий Zabbix
      get_url:
        url: "https://repo.zabbix.com/zabbix/{{ zabbix_major_version }}/rhel/8/x86_64/zabbix.repo"
        dest: /etc/yum.repos.d/zabbix.repo
        mode: '0644'

    - name: Очищаем кэш yum
      command: yum clean all

    - name: Обновляем метаданные yum
      command: yum makecache

    - name: Устанавливаем Zabbix Agent 2
      yum:
        name: zabbix-agent2
        state: latest
        disable_gpg_check: yes
      register: install_result
      until: install_result is succeeded
      retries: 3
      delay: 10

    - name: Настраиваем конфигурацию агента
      template:
        src: zabbix_agent2.conf.j2
        dest: /etc/zabbix/zabbix_agent2.conf
        owner: zabbix
        group: zabbix
        mode: '0644'
      notify: Restart Zabbix Agent 2

    - name: Проверяем, что сервис запущен
      systemd:
        name: zabbix-agent2
        enabled: true
        state: started

  handlers:
    - name: Restart Zabbix Agent 2
      systemd:
        name: zabbix-agent2
        state: restarted
